version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: MattLi2024!!
      MYSQL_DATABASE: sultanne
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
  mongodb_data: